export const POEM_LIST_REQUEST = "POEM_LIST_REQUEST";
export const POEM_LIST_SUCCESS = "POEM_LIST_SUCCESS";
export const POEM_LIST_FAIL = "POEM_LIST_FAIL";

export const SINGLE_POEM_REQUEST = "SINGLE_POEM_REQUEST";
export const SINGLE_POEM_SUCCESS = "SINGLE_POEM_SUCCESS";
export const SINGLE_POEM_FAIL = "SINGLE_POEM_FAIL";

export const SINGLE_POEM_VOTES = "SINGLE_POEM_VOTES";
export const SINGLE_POEM_UPVOTES_FAIL = "SINGLE_POEM_UPVOTES";
export const SINGLE_POEM_DOWNVOTES_FAIL = "SINGLE_POEM_DOWNVOTES";
export const SINGLE_POEM_VOTES_RESET = "SINGLE_POEM_VOTES_RESET";

export const ADD_POEM_REQUEST = "ADD_POEM_REQUEST";
export const ADD_POEM_SUCCESS = "ADD_POEM_SUCCESS";
export const ADD_POEM_FAIL = "ADD_POEM_FAIL";
export const ADD_POEM_RESET = "ADD_POEM_RESET";

export const POEM_CREATE_COMMENT_REQUEST = "POEM_CREATE_COMMENT_REQUEST";
export const POEM_CREATE_COMMENT_SUCCESS = "POEM_CREATE_COMMENT_SUCCESS";
export const POEM_CREATE_COMMENT_FAIL = "POEM_CREATE_COMMENT_FAIL";
export const POEM_CREATE_COMMENT_RESET = "POEM_CREATE_COMMENT_RESET";
